events {}

http {

    upstream url_shortner {
        server host.docker.internal:8181;
        server host.docker.internal:8182;
        server host.docker.internal:8183;
        server host.docker.internal:8184;
        server host.docker.internal:8185;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://url_shortner;
        }
    }
}